plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.chaquo.python apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

project(':app').tasks.matching { it.name ==~ /assemble.+Release/ }.configureEach {
    doLast {
        copy {
            from fileTree("$rootDir/app/build/outputs/apk") { include '**/release/*.apk' }
            into "$rootDir/Release/apk"
            eachFile { it.path = it.name }
            includeEmptyDirs = false
        }
    }
}

subprojects {
    tasks.whenTaskAdded { task ->
        if (task.name.contains("check") && task.name.contains("AarMetadata")) {
            task.enabled = false
        }
    }
}

tasks.register('buildChaquo', Exec) {
    doFirst {
        delete "$rootDir/chaquo_build/catvod/src", "$rootDir/chaquo_build/chaquo/src"
        copy {
            from "$rootDir/catvod/src"
            into "$rootDir/chaquo_build/catvod/src"
        }
        copy {
            from "$rootDir/catvod/proguard-rules.pro"
            into "$rootDir/chaquo_build/catvod"
        }
        copy {
            from "$rootDir/chaquo/src"
            into "$rootDir/chaquo_build/chaquo/src"
        }
        copy {
            from "$rootDir/chaquo/requirements.txt"
            into "$rootDir/chaquo_build/chaquo"
        }
        copy {
            from "$rootDir/chaquo/proguard-rules.pro"
            into "$rootDir/chaquo_build/chaquo"
        }
        println "Chaquopy source files synchronized to chaquo_build."
    }

    workingDir "$rootDir/chaquo_build"
    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'gradlew.bat :chaquo:assembleRelease'
    } else {
        commandLine './gradlew', ':chaquo:assembleRelease'
    }

    doLast {
        copy {
            from "$rootDir/chaquo_build/chaquo/build/outputs/aar/chaquo-release.aar"
            into "$rootDir/app/libs"
        }
        println "Chaquopy AAR compiled and copied to app/libs/chaquo-release.aar"
    }
}
