org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useFullClasspathForDexingTransform=true
systemProp.https.protocols=TLSv1.2,TLSv1.3,TLSv1.1,TLSv1

