plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.github.catvod.crawler'

    compileSdk {
        version = release(36) {
            it.minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk 23
        targetSdk 36
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    api libs.annotation
    api libs.brotli
    api libs.bundles.okhttp
    api libs.gson
    api libs.guava
    api libs.juniversalchardet
    api libs.logger
    api libs.preference
    api libs.sardine
    api libs.smbj
    api libs.startup
    api libs.zxing.core
    coreLibraryDesugaring libs.desugar
}