plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.fongmi.android.tv.quickjs'

    compileSdk {
        version = release(36) {
            it.minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk 23
        targetSdk 36
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':catvod')
    implementation libs.quickjs.android
    implementation libs.quickjs.java
    coreLibraryDesugaring libs.desugar
}